// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quan_li_ky_tuc_xa.Models.Data;

#nullable disable

namespace Quan_li_ky_tuc_xa.Migrations
{
    [DbContext(typeof(KTXContext))]
    partial class KTXContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Ban_quan_li", b =>
                {
                    b.Property<string>("MaQL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiamDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQL");

                    b.HasIndex("MaGiamDoc")
                        .IsUnique();

                    b.ToTable("BanQuanLi", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Dich_vu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Hoa_don", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Hop_dong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVienQuanLi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.HasIndex("MaNhanVienQuanLi");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MaQL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaQL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaToa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTruongPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaToa");

                    b.HasIndex("MaTruongPhong")
                        .IsUnique();

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Sinh_Vien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaPhong");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Toa", b =>
                {
                    b.Property<string>("MaToa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVienQuanLi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaToa");

                    b.HasIndex("MaNhanVienQuanLi")
                        .IsUnique();

                    b.ToTable("Toa", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Ban_quan_li", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", "Giam_doc")
                        .WithOne("Ban_Quan_Li_Giam_doc")
                        .HasForeignKey("Quan_li_ky_tuc_xa.Models.Entities.Ban_quan_li", "MaGiamDoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Giam_doc");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Hoa_don", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Hop_dong", "Hop_Dong")
                        .WithOne("Hoa_Don")
                        .HasForeignKey("Quan_li_ky_tuc_xa.Models.Entities.Hoa_don", "MaHopDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hop_Dong");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Hop_dong", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Dich_vu", "Dich_Vu")
                        .WithOne("Hop_Dong")
                        .HasForeignKey("Quan_li_ky_tuc_xa.Models.Entities.Hop_dong", "MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", "Nhan_Vien")
                        .WithMany("Hop_Dongs")
                        .HasForeignKey("MaNhanVienQuanLi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Phong", "Phong")
                        .WithMany("Hop_Dongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Sinh_Vien", "Sinh_Vien")
                        .WithMany("Hop_Dongs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dich_Vu");

                    b.Navigation("Nhan_Vien");

                    b.Navigation("Phong");

                    b.Navigation("Sinh_Vien");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Ban_quan_li", "Ban_Quan_Li")
                        .WithMany("Nhan_Viens")
                        .HasForeignKey("MaQL")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ban_Quan_Li");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Phong", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Toa", "Toa")
                        .WithMany("Phongs")
                        .HasForeignKey("MaToa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Sinh_Vien", "Truong_phong")
                        .WithOne("TruongPhong")
                        .HasForeignKey("Quan_li_ky_tuc_xa.Models.Entities.Phong", "MaTruongPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Toa");

                    b.Navigation("Truong_phong");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Sinh_Vien", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Phong", "Phong")
                        .WithMany("Sinh_Viens")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Toa", b =>
                {
                    b.HasOne("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", "Nhan_Vien")
                        .WithOne("Toa")
                        .HasForeignKey("Quan_li_ky_tuc_xa.Models.Entities.Toa", "MaNhanVienQuanLi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Ban_quan_li", b =>
                {
                    b.Navigation("Nhan_Viens");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Dich_vu", b =>
                {
                    b.Navigation("Hop_Dong")
                        .IsRequired();
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Hop_dong", b =>
                {
                    b.Navigation("Hoa_Don")
                        .IsRequired();
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Nhan_vien", b =>
                {
                    b.Navigation("Ban_Quan_Li_Giam_doc");

                    b.Navigation("Hop_Dongs");

                    b.Navigation("Toa")
                        .IsRequired();
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Phong", b =>
                {
                    b.Navigation("Hop_Dongs");

                    b.Navigation("Sinh_Viens");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Sinh_Vien", b =>
                {
                    b.Navigation("Hop_Dongs");

                    b.Navigation("TruongPhong");
                });

            modelBuilder.Entity("Quan_li_ky_tuc_xa.Models.Entities.Toa", b =>
                {
                    b.Navigation("Phongs");
                });
#pragma warning restore 612, 618
        }
    }
}
